"""update assets

Revision ID: 3a1f6cbf51bc
Revises: 6381d6c33e2c
Create Date: 2022-03-27 21:59:11.973901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1f6cbf51bc'
down_revision = '6381d6c33e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('cashflow', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'cashflow')
    op.drop_column('assets', 'cost')
    # ### end Alembic commands ###
