"""create assets

Revision ID: 6381d6c33e2c
Revises: b15abf711575
Create Date: 2022-03-27 21:53:11.109969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6381d6c33e2c'
down_revision = 'b15abf711575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assettypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20, collation=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20, collation=0), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['assettypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('assettypes')
    # ### end Alembic commands ###
