"""add children_expense to Job

Revision ID: b15abf711575
Revises: 44080a5577ca
Create Date: 2022-03-16 10:56:23.043320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15abf711575'
down_revision = '44080a5577ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('children_expenses', sa.Numeric(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'children_expenses')
    # ### end Alembic commands ###
