"""empty message

Revision ID: f81186b2e4f4
Revises: 
Create Date: 2022-05-17 14:43:40.120205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81186b2e4f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('cashflow', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('home_mortgage_payment', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('school_loan_payment', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('car_loan_payment', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('credit_card_payment', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('bank_loan_payment', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('children', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('children_expenses', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('savings', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('home_mortgage', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('school_loans', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('car_loans', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('credit_card_debt', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('payday', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('uname', sa.String(length=80), nullable=True),
    sa.Column('fname', sa.String(length=80), nullable=True),
    sa.Column('lname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('profession')
    op.drop_table('opportunity')
    # ### end Alembic commands ###
